### ISSUE TITLE
LogRTMPPublisher: Error: Cloud not start to record game viewport.

### ISSUE THREAD

**Issue by kemal3ds** [hl1282456555/Streaming#1]
Hi, i tried demo project but it gave me an error.
LogRTMPPublisher: Error: Cloud not start to record game viewport.
i just compiled and run, is there any extra step should i do?

**Comment by hl1282456555** [comment]
You should package this project, then you can test it.
The project cast GEngine to UGameEngine, so you cant initialize the recorder when you play the game in editor.
