### ISSUE TITLE
LogRTMPPublisher Error

### ISSUE THREAD

**Issue by eusru** [hl1282456555/Streaming#2]
Write access denied for stream

**Comment by hl1282456555** [comment]
Any logs or more informations?

**Comment by eusru** [comment]
> Any logs or more informations?



> Any logs or more informations?

when I try play RTMP Video，the error happened.
The RTMP Video can play on Potplayer and VLC player

**Comment by hl1282456555** [comment]
This plugin is not designed for play a RTMP video.
It just work for recording your game viewport and live streaming.

**Comment by eusru** [comment]
> This plugin is not designed for play a RTMP video. It just work for recording your game viewport and live streaming.

thank u
