### ISSUE TITLE
How to save as file?

### ISSUE THREAD

**Issue by waterfu1124** [hl1282456555/Streaming#3]
I package the project then play it,but how to save the file?

**Comment by hl1282456555** [comment]
> I package the project then play it,but how to save the file?

GameViewportRecorder: Record game viewport output and give you bgra corlo data. Only useful in runtime.

Maybe you should check this component.

**Comment by waterfu1124** [comment]
> > I package the project then play it,but how to save the file?
> 
> GameViewportRecorder: Record game viewport output and give you bgra corlo data. Only useful in runtime.
> 
> Maybe you should check this component.

You mean GeneralSetting->GameViewportClient? 
A bit embarrassed, i did't find GameViewportRecorder component in the project.

**Comment by hl1282456555** [comment]
> > > I package the project then play it,but how to save the file?
> > 
> > 
> > GameViewportRecorder: Record game viewport output and give you bgra corlo data. Only useful in runtime.
> > Maybe you should check this component.
> 
> You mean GeneralSetting->GameViewportClient? A bit embarrassed, i did't find GameViewportRecorder component in the project.

Sorry, my mistake, GameViewportRecorder is not a component.

It is a native c++ class in /Plugins/RTMP/Source/RTMP/Public/GameViewportRecorder.h

This class is not expose to blueprint, so you should write some c++ code.

**Comment by waterfu1124** [comment]
> > > > I package the project then play it,but how to save the file?
> > > 
> > > 
> > > GameViewportRecorder: Record game viewport output and give you bgra corlo data. Only useful in runtime.
> > > Maybe you should check this component.
> > 
> > 
> > You mean GeneralSetting->GameViewportClient? A bit embarrassed, i did't find GameViewportRecorder component in the project.
> 
> Sorry, my mistake, GameViewportRecorder is not a component.
> 
> It is a native c++ class in /Plugins/RTMP/Source/RTMP/Public/GameViewportRecorder.h
> 
> This class is not expose to blueprint, so you should write some c++ code.

Got it ,thanks a lot
